"""Add chunk test cases

Revision ID: bef4f254435d
Revises: 7d97a9392f2b
Create Date: 2026-02-28 06:44:40.393036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bef4f254435d'
down_revision: Union[str, Sequence[str], None] = '7d97a9392f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_test_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('chunks', 'test_case_input')
    op.drop_column('chunks', 'test_case_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('test_case_output', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('test_case_input', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('chunk_test_cases')
    # ### end Alembic commands ###
