"""resolve_relationship_conflicts

Revision ID: e010f5d8dfa5
Revises: c48ea95cb4e7
Create Date: 2026-02-09 13:11:16.449054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e010f5d8dfa5'
down_revision: Union[str, Sequence[str], None] = 'c48ea95cb4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
