"""Integrate tags and categories for riddles and questions

Revision ID: fcbb89d73263
Revises: ac60f589df83
Create Date: 2026-02-15 18:28:18.491686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcbb89d73263'
down_revision: Union[str, Sequence[str], None] = 'ac60f589df83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_categories',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'category_id')
    )
    op.create_table('question_tags',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.create_table('riddle_tags',
    sa.Column('riddle_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['riddle_id'], ['riddles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('riddle_id', 'tag_id')
    )
    op.drop_column('questions', 'tag')
    op.drop_column('questions', 'category')
    op.drop_column('riddles', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riddles', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('riddle_tags')
    op.drop_table('question_tags')
    op.drop_table('question_categories')
    # ### end Alembic commands ###
